name: Python CI/CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Python Program Quality Control
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing code with flake8
        run: |
          flake8
      - name: Running tests with pytest
        run: |
          pytest
  test:
    name: Unitest for python
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependcy
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest